### ISSUE TITLE
demo 运行不了

### ISSUE THREAD

**Issue by SiterZzz** [asomePubcode/ALLiveLogger#1]
pod  install  直接报错

**Comment by asomeLiao** [comment]
麻烦截下错误信息看看

**Comment by asomeLiao** [comment]
@SiterZzz 按下面步骤

下载代码
$git clone https://github.com/asomePubcode/Logger.git
进入工程根目录
$cd Logger/Logger
安装依赖
$pod install

**Comment by SiterZzz** [comment]
> @SiterZzz 按下面步骤
> 
> 下载代码
> $git clone https://github.com/asomePubcode/Logger.git
> 进入工程根目录
> $cd Logger/Logger
> 安装依赖
> $pod install
就是这样操作的

**Comment by SiterZzz** [comment]
@asomeLiao   就是按照你说的那样去操作的

**Comment by asomeLiao** [comment]
@SiterZzz 错误贴上来看看呗

**Comment by SiterZzz** [comment]
@asomeLiao   还有个问题  如果 我两台手机在同一个局域网 这个  怎么判断是那个手机的日志呢

**Comment by SiterZzz** [comment]
@asomeLiao 

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Logger-iphone' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for Logger
    pod 'Log',:path => '../Modules/Log/'
    pod 'LiveLog',:path => '../Modules/LiveLog/'
end
```

### Error

```
RuntimeError - [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/Users/stw/.rvm/gems/ruby-2.4.0@global/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:321:in `configure_with_plist'
/Users/stw/.rvm/gems/ruby-2.4.0@global/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:262:in `new_from_plist'
/Users/stw/.rvm/gems/ruby-2.4.0@global/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Users/stw/.rvm/gems/ruby-2.4.0@global/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Users/stw/.rvm/gems/ruby-2.4.0@global/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:299:in `each'

**Comment by asomeLiao** [comment]
> @asomeLiao 还有个问题 如果 我两台手机在同一个局域网 这个 怎么判断是那个手机的日志呢

同一个局域网2台手机IP肯定是不一样的嘛

**Comment by SiterZzz** [comment]
我傻逼了 问这样的问问题。

**Comment by asomeLiao** [comment]
> xcodeproj



> @asomeLiao
> 
> ### Podfile
> ```ruby
> # Uncomment the next line to define a global platform for your project
> # platform :ios, '9.0'
> 
> target 'Logger-iphone' do
>     # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
>     # use_frameworks!
>     
>     # Pods for Logger
>     pod 'Log',:path => '../Modules/Log/'
>     pod 'LiveLog',:path => '../Modules/LiveLog/'
> end
> ```
> 
> ### Error
> ```
> RuntimeError - [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
> If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
> /Users/stw/.rvm/gems/ruby-2.4.0@global/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:321:in `configure_with_plist'
> /Users/stw/.rvm/gems/ruby-2.4.0@global/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:262:in `new_from_plist'
> /Users/stw/.rvm/gems/ruby-2.4.0@global/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
> /Users/stw/.rvm/gems/ruby-2.4.0@global/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
> /Users/stw/.rvm/gems/ruby-2.4.0@global/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:299:in `each'
> ```

网上找到你类似的错误，这个应该是cocoapod 与Xcode 10兼容性问题。
https://stackoverflow.com/questions/52199554/cocoapods-with-xcode-10-runtimeerror-xcodeproj-doesnt-know-about-the-following

**Comment by SiterZzz** [comment]
现在还有个问题  我项目里面有  fmdb  现在导入冲突

**Comment by SiterZzz** [comment]
@asomeLiao

**Comment by SiterZzz** [comment]
我现在直接导入我的项目里面了，但是和你的FMDB依赖冲突了

**Comment by asomeLiao** [comment]
> 现在还有个问题 我项目里面有 fmdb 现在导入冲突

截图看看？或者你把FMDB部分移除掉呗。我们项目也有FMDB

**Comment by SiterZzz** [comment]
@asomeLiao  我把你的依赖移除了  0.0

**Comment by asomeLiao** [comment]
> @asomeLiao 我把你的依赖移除了 0.0

你不需要日志存数据库的话。确实没必要加进去的。
