### ISSUE TITLE
求一个重写NSLog的宏

### ISSUE THREAD

**Issue by SiterZzz** [asomePubcode/ALLiveLogger#3]
求一个重写NSLog的宏调用DDLogInfo，我自己试了一下  功底不行，求大佬拉一把。

**Comment by asomeLiao** [comment]
> 求一个重写NSLog的宏调用DDLogInfo，我自己试了一下 功底不行，求大佬拉一把。

![image](https://user-images.githubusercontent.com/17819753/62452812-832fa200-b7a3-11e9-9d03-ce786e5a84ef.png)
这样就可以了啊

**Comment by SiterZzz** [comment]
@asomeLiao    是这样的，我手里还有一个老项目，没有管理日志，全是调用的系统的NSLog，我想方便的接入DDLogInfo。

**Comment by asomeLiao** [comment]
> @asomeLiao 是这样的，我手里还有一个老项目，没有管理日志，全是调用的系统的NSLog，我想方便的接入DDLogInfo。
按上面回复的截图那样定义一下看看。

**Comment by SiterZzz** [comment]
#define NSLog(FORMAT, ...) DDLogInfo((@"[路径:%s]\n" "[函数名:%s]\n" "[行号:%d] \n" FORMAT), [[NSString stringWithFormat:@"%s", __FILE__].lastPathComponent UTF8String], __FUNCTION__, __LINE__, ##__VA_ARGS__);
