### ISSUE TITLE
打包后安装 日志不打印

### ISSUE THREAD

**Issue by SiterZzz** [asomePubcode/ALLiveLogger#4]
打包后安装日志不打印，连socket都没有连接，请问连接的条件是debug模式？

**Comment by asomeLiao** [comment]
没有设置啊，我下午看看

**Comment by asomeLiao** [comment]
我这边看了release模式并没有问题，你检查下你的网络。电脑上看看能不能ping之类的。

**Comment by asomeLiao** [comment]
> 打包后安装日志不打印，连socket都没有连接，请问连接的条件是debug模式？

我也遇到了一个包在release 环境下无打印的问题，结果发生是其他库中也定义了DDLogLevel ddLogLevel。默认在release下面使用的level是warning，所以导致级别大于warning的都无法打印。看看你那边是不是这个问题。
`
#ifdef DEBUG

DDLogLevel ddLogLevel = DDLogLevelVerbose;

#else

DDLogLevel ddLogLevel = DDLogLevelWarning;

#endif
`
