### ISSUE TITLE
支持XCGLogger的实时打印吗

### ISSUE THREAD

**Issue by xuegeliu** [asomePubcode/ALLiveLogger#5]
pod 'XCGLogger', '6.1.0'                  # 日志输出

**Comment by asomeLiao** [comment]
> ```
> pod 'XCGLogger', '6.1.0'                  # 日志输出
> ```

现在暂时没有支持，但是我看了下XCGLogger文档。也是可以实现实时输出到网页。

我准备近期做成一个跟日志库不相关的工具。

**Comment by xuegeliu** [comment]
oc、swift混编项目swift4.0报错
Implicit declaration of function 'LOG_OBJC_MAYBE' is invalid in C99

**Comment by asomeLiao** [comment]
> oc、swift混编项目swift4.0报错
> Implicit declaration of function 'LOG_OBJC_MAYBE' is invalid in C99

![image](https://user-images.githubusercontent.com/17819753/62851404-8df4b480-bd18-11e9-999a-46ddbaaf4262.png)
最新的commit，有个简单的兼容XCGLogger. 你可以尝试下

**Comment by xuegeliu** [comment]
老哥啥时候支持下XCGLogger啊，或者要写啥代码才能跟你这个实时搭配啊

**Comment by asomeLiao** [comment]
> 老哥啥时候支持下XCGLogger啊，或者要写啥代码才能跟你这个实时搭配啊

已经pod 'ALLiveLogger',支持了DDLog,XCGLogger，demo里面有使用，你看看吧

**Comment by xuegeliu** [comment]
给力，改天试试
